version: '3.4'

services:
  intelitradermvc:
    image: ${DOCKER_REGISTRY-}intelitraderapi
    build:
      context: .
      dockerfile: .
    ports:
      - "5001:5001"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=senai@132
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"