version: '3.9'

services:
  intelitradermvc:
    build:
      context: ./IntelitraderAPI
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=senai@132
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1450:1433"